### ISSUE TITLE
Purpose of the project

### ISSUE THREAD

**Issue by jjb** [rack/rack-contrib#104] opened 2015-06-14 19:25 UTC
*Background: for a long time there was a maintainer vacuum in rack-contrib. This was brought up in #72, resulting in @chneukirchen adding several people as maintainers. You can see all the maintainers [here](https://github.com/orgs/rack/teams/rack-contrib).*

I wonder if we should discuss and document what the purpose of rack-contrib is? If it's for any and all middleware that seem Pretty Useful and are Well Tested, then that means the project can grow and grow, increasing the number of projects that a team of fixed size is responsible for maintaining.

In the rack middleware ecosystem there are three places a middleware can be:

1. [Within rack](https://github.com/rack/rack/tree/master/lib/rack)
2. In rack-contrib
3. Out in the wild

n.b. The file structure of the rack project doesn't delineate between code which implements "rack itself" and code which is implementing various middleware, although there isn't really much to "rack itself" anyway I suppose.

What dictates if a library is worthy of being in 1 vs. 2? 2 vs. 3?

I could start to brainstorm some criteria for the future. I wonder if there was any official or unofficial policy which resulted in the current state of the project?

/cc @chneukirchen @rtomayko @jeremy @josh @raggi

**Comment by raggi** [comment] 2015-06-15 00:34
most middleware should not be in 1. We have middleware in rack that should never really have been middleware - we should have pushed on server authors directly. Specific things that caused chris and I and users pain over the years:

 * Static content serving - there's just too many opinions about special character and characterset handling, desires for indexing patterns, automatic redirects, etc.
 * Content-Length calculation - there's no efficient way to implement this in SPEC and it was more of a workaround for shitty server rules than a long intended solution to other problems such as "http conformance"
 * Same deal for Chunked. The problem here is that when you introduce pipelining and so on, then chunked and content length need knowledge of the connection state in order to perform full valid HTTP. There's one case from 2616 (I believe is still present in the new RFCs, but I haven't looked specifically), where both CL is not given and neither is Chunked, where Connection:close must be specified. If this were passed to a server and it is in the middle of a pipeline, it should return a 500 to the user, but there's not much an application author would know about it. The saddest thing is that this is what the text/event-stream specification calls out for in a "note:" section, so while it's a "minor case" that many load balancers don't even handle, the design cannot fit the specification. Finally, it is far more efficient for servers to have sane rules for this, and for the rack spec to simply deny the user unreasonable control - specification by deliberate action instead of by inaction. IDB is a pain for everyone - server authors think otherwise, but just ask someone who cares about correctness - I know it took evan a while with puma.
 * Config - I don't think I've ever seen it used by anyone else.
 * Deflater - again, seriously, server concern.
 * Head - again, server concern, or server should just ignore it. Users can do this so easily this middleware is far too superfluous.
 * Reloader - a huge pain in the ass to cover all the edge cases, a project to handle this would be better, that way it could tie into dependencies and so on.
 * Sendfile - goes with the static serving stuff above.

Contrib could contain more of the above, but I think the grab bag libs are still painful.

You could for one step one day in rack move the http conformance stuff into something like rack-http, the config stuff into rack-config, all the file, directory, static and sendfile middleware into rack-static, and then leave reloader to whoever really wants to own that pain.

Now of course, there is another side, that is the size of some of these gems would be 90+% overhead for having more .gem's to install. Sure. That's all a taste thing, The answer really comes down to who wants to maintain what and how. That's others choice these days.

Finally @tenderlove and @spastorino as current rack/rack maintainers should see this.

**Comment by chneukirchen** [comment] 2015-06-15 09:03
> We have middleware in rack that should never really have been middleware - we should have pushed on server authors directly.

This was directly caused by me, who refactored a half-done never-released web framework into what now is Rack and thought these would be useful things. ;) Lession learned.

**Comment by spastorino** [comment] 2015-06-15 18:00
I'd move most of the middleware to 3). Maybe we can have a rack-contrib repo that is just a gemspec with dependencies to a set of things that are in 3, the ones that we think are important and are good quality solutions.

**Comment by jjb** [comment] 2015-06-15 19:30
Thanks for the thoughts so far everyone. It seems that we all like @raggi's idea of splitting out many of the middleware from the main rack project into sub-projects. AFAIK, this reorganization can start without needing to do a major version release (because the existing rack gem would simply require the others until the next major version). There could probably be immediate benefits. The "core" code will be easier to read and change. The sub-projects would be more likely to get attention and contributions. For example, I would hope that Heroku would take some ownership of Deflater, and maybe when rack 2 (or whatever) comes around it would be moved over to their ownership completely.

rack-contrib already doesn't have an expressed goal. If these new subprojects are made, it seems that this would become even more so the case. Maybe some (most?) of the middleware currently in rack-contrib could be redistributed to these new subprojects. Those that don't make the cut would get branched off into their own sub projects and declared unmaintained. If a third-party maintainer wants to pick it up, then it will be dropped from the rack organization completely.

The question would still remain: what middleware warrants inclusion in a rack-* project? I propose this as a start:

* For patterns that are very common, provide a reference implementation so that developers do not have to reinvent the wheel.
* For patterns that are very useful or interesting, provide a well-done implementation.

(Obviously there is great overlap between these two cases, but it seemed worthwhile to express them individually.)

**Comment by raggi** [comment] 2015-06-15 22:45
`This was directly caused by me, who refactored a half-done never-released web framework into what now is Rack and thought these would be useful things. ;) Lession learned.`

Chris - I think at the time this was absolutely the correct thing to do, it's just unfortunate that we learned more about it after we had too many users to make adjustments. There was also that strange period in ruby history where communicating changes for webrick was too damned hard. Oh, hang on.

**Comment by mpalmer** [comment] 2015-06-17 04:52
I agree that, in a perfect world, grab-bag libs are somewhat painful.  However, when a useful middleware can be ten lines of production code, making an individual gem for each of those seems like overkill.

My take on the purpose of `rack-contrib` is to act as a place to collect middleware and other Rack-related code which is not of sufficient size to warrant the overhead of a package of its own.  I'm well aware that that is a very subjective definition, and I'm sure there will be some haggling around the edges over time as to what is appropriate (or not).

For the maintenance issue (of the project getting larger and larger with a fixed-size team), I'm willing to believe in the power of the Internet to provide sufficient help to keep things going, should it turn out that `rack-contrib` gets huge.  We're well short of that point now, though.

**Comment by jjb** [comment] 2015-06-17 13:52
@mpalmer Including a size in the criteria for what dictates what goes in 1, 2, or 3 seems like an idea with potential. If the rack maintainers people on this thread don't decide to do a reorg on rack proper, then we could in the meantime have a size limit guideline for rack-contrib. Here are the current counts:

```
➔ wc -l *
      46 accept_format.rb
      85 access.rb
      20 backstage.rb
      16 bounce_favicon.rb
      37 callbacks.rb
      38 common_cookies.rb
      16 config.rb
      50 cookies.rb
      39 csshttprequest.rb
     137 deflect.rb
      12 evil.rb
      32 expectation_cascade.rb
      14 garbagecollector.rb
      47 host_meta.rb
     110 jsonp.rb
      16 lighttpd_script_name_fix.rb
      42 locale.rb
     114 mailexceptions.rb
     143 nested_params.rb
      18 not_found.rb
      40 post_body_content_type_parser.rb
      25 printout.rb
      30 proctitle.rb
      98 profiler.rb
      44 relative_redirect.rb
      59 response_cache.rb
      24 response_headers.rb
      49 route_exceptions.rb
      31 runtime.rb
     142 sendfile.rb
      63 signals.rb
      80 simple_endpoint.rb
      93 static_cache.rb
      25 time_zone.rb
      36 try_static.rb
```

**Comment by mpalmer** [comment] 2015-06-18 05:04
I wouldn't want to put a *hard* limit on the "size" of a contributed module... that way lies madness (especially in a one-liner-rich language like Ruby...).  I would definitely expect to tell someone who wanted to include some multi-file monster to build their own gem, though.

**Comment by raggi** [comment] 2015-06-18 18:03
So here's another way to look at it:

If the proposed addition grab bag contains no external dependencies, and it fits comfortably in one file, then great. If it's much bigger or has external dependencies, a new gem may be better.

If we stop auto-loading, then this means the grab bag has little runtime overhead following these rules.

All prior comments are also valid views, IMO.

HTH

**Comment by mpalmer** [comment] 2015-06-19 09:08
Yeah, external dependencies do cause all sorts of problems.  I'd be strongly disinclined to add any new middleware that had external deps.  I don't like to say "never", because I don't have that good an imagination, but I certainly can't think of a circumstance in which I'd think it were a good idea.

A vague thought I have had for a 2.0 release is to cull any middleware in `rack-contrib` that has external deps (there's only a few of them) into separate gems, kept under `rack-contrib` team maintenance.  That's a very, *very* vague thought, though.

**Comment by raggi** [comment] 2015-06-19 17:52
sgtm, and thanks for doing all this.

**Comment by jjb** [comment] 2015-06-22 17:07
Okay, I've created #105 with some proposed criteria for inclusion, take a look.

Feel free to nit-pick my wording on anything at all. Just leave comments and I will tweak it.

**Comment by mpalmer** [comment] 2015-06-23 02:57
Does anyone wish to add anything further to this issue, or should we close it off?  It appears to have spawned some good outcomes.

**Closed** 2015-07-17 01:55 UTC
